# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1126e3c1993dd04d48ecb107efbc00ed0b50cecfa4e3c87320203fadd2dbeaa78deeb10601757d1dc6f74d0a270217d500b78d40b3f22a4e704fca0fb0c793b2

test:
  secret_key_base: 14b1939248bfa19a7afd3c5c9acea4b5230c3d676ba15fc13c0203142fe668bf033e1c76cb34315cfa32b64ee05d843bb517a329f89f3574c838eb3a4d428bbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
